config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users

  resources :products, only: [:index, :show]

  post :search, to: "searches#show"
  get :search, to: "searches#show"

  namespace :stripe_event do
    post "/stripe/webhook", to: "webhook#event"
  end

  resource :checkout, only: [:show, :create] do
    resource :payment, only: :show
  end

  namespace :carts do
    resource :add, only: :create
    resource :reduce, only: :create
    resource :remove, only: :destroy
  end

  get 'contact_us/index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user, optional: true
  has_many :cart_items, dependent: :destroy

  enum status: {
    checkout_pending: 0,
    payment_pending: 1,
    payment_complete: 2,
    fullfilled: 3,
    cancelled: 4
  }

  def quantity
    cart_items.sum(&:quantity)
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  include ActionView::RecordIdentifier

  belongs_to :cart
  belongs_to :product

  after_create_commit do
    update_item_count
    update_total_price
  end

  after_update_commit do
    update_item_count
    update_total_price
    broadcast_replace_to cart,
                         target: dom_id(self, "quantity"),
                         partial: "cart/item_quantity",
                         locals: { cart_item: self }
  end

  after_destroy_commit do
    broadcast_remove_to cart
    update_item_count
    update_total_price
  end

  def total_price
    quantity.to_i * product.price.to_f
  end

  private

  def update_total_price
    broadcast_replace_to cart,
                         target: "total_price",
                         partial: "cart/total_price",
                         locals: { current_cart: cart }
  end

  def update_item_count
    broadcast_replace_to cart,
                         target: "cart_count",
                         partial: "cart/item_count",
                         locals: { count: cart.quantity }
  end
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/product_search.rb
class ProductSearch
  def self.call(params)
    new(params).call
  end

  def initialize(params)
    @params = params
  end

  def call
    products
      .where(search_condition)
      .where(price_condition)
      .order(sort_condition)
  end

  private

  def products
    @products ||= Product.all
  end

  def search_condition
    return unless @params.dig(:search, :query)

    ["name LIKE ?", "%#{@params.dig(:search, :query)}%"]
  end

  def price_condition
    return unless @params.dig(:search, :price)
    conditions = [].tap do |array|
      array << (..100) if @params.dig(:search, :price).include?("lt100")
      array << (100..250) if @params.dig(:search, :price).include?("bewteen100and250")
      array << (250..) if @params.dig(:search, :price).include?("gt250")
    end
    { price: conditions }
  end

  def sort_condition
    return unless @params.dig(:search, :sort)

    case @params.dig(:search, :sort)
    when "price_lth"
      { price: :asc }
    when "price_htl"
      { price: :desc }
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :cart
end

app/models/webhooks/checkout.rb
module Webhooks
  class Checkout
    def initialize(event)
      @event = event
    end

    def call
      cart = Cart.find_by!(stripe_session_id: object.id)
      cart.payment_complete!
      
    end

    private

    def object
      @event.data.object
    end

  end
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_cart
    if user_signed_in?
      cart = Cart.find_or_create_by(user: current_user)
    else
      token = cookies[:cart_token] || SecureRandom.alphanumeric(10)
      cookies[:cart_token] ||= token
      cart = Cart.find_or_create_by(token: token)
    end
    transfer_items_from_temp_cart(cart)
    cart
  end
  
  helper_method :current_cart

  def after_sign_out_path_for(resource)
    root_path
  end

  private

  def transfer_items_from_temp_cart(user_cart)
    if cookies[:cart_token].present?
      temp_cart = Cart.find_by(token: cookies[:cart_token])
      if temp_cart.present? && temp_cart != user_cart
        temp_cart.cart_items.update_all(cart_id: user_cart.id)
        temp_cart.destroy
        cookies.delete(:cart_token)
      end
    end
  end
end

app/controllers/carts/adds_controller.rb
module Carts
  class AddsController < ApplicationController
    def create
      if product_found?
        cart_item = current_cart.cart_items.find_or_initialize_by(product_id: params[:product])
        cart_item.quantity += 1
        cart_item.save
      end
    end

    private

    def product_found?
      Product.exists?(params[:product])
    end
  end
end

app/controllers/carts/reduces_controller.rb
module Carts
  class ReducesController < ApplicationController
    def create
      if product_found?
        cart_item = current_cart.cart_items.find_or_initialize_by(product_id: params[:product])
        cart_item.quantity = [cart_item.quantity - 1, 1].max
        cart_item.save
      end
    end

    private

    def product_found?
      Product.exists?(params[:product])
    end
  end
end

app/controllers/carts/removes_controller.rb
module Carts
  class RemovesController < ApplicationController
    def destroy
      if product_found?
        cart_item = current_cart.cart_items.find_by(product_id: params[:product])
        cart_item.destroy
      end
    end

    private

    def product_found?
      Product.exists?(params[:product])
    end
  end
end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  before_action :authenticate_user!, except: :show

  def show
  end

  def create
    if user_signed_in?
      session = Stripe::Checkout::Session.create(
        billing_address_collection: :auto,
        mode: :payment,
        payment_method_types: ['card'],
        line_items: cart_items,
        success_url: checkout_payment_url,
        cancel_url: root_url
      )

      current_cart.update!(stripe_session_id: session.id)
      redirect_to session.url, allow_other_host: true
    else
      session[:redirect_to_checkout] = true
      redirect_to new_user_session_path
    end
  end

  private

  def cart_items
    current_cart.cart_items.map do |cart_item|
      {
        price_data: {
          currency: "gbp",
          product_data: {
            name: cart_item.product.name
          },
          unit_amount: cart_item.product.price.to_i * 100
        },
        quantity: cart_item.quantity
      }
    end 
  end
end

app/controllers/contact_us_controller.rb
class ContactUsController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def show
    current_cart&.payment_pending!
    current_user.cart.cart_items.destroy_all if current_user&.cart
    cookies.delete(:cart_token)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.page(params[:page]).per(12)
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def show
    @products = ProductSearch.call(params)
    respond_to do |format|
      format.turbo_stream {
        render turbo_stream: turbo_stream.replace(
          "products_display",
          partial: "products/show",
          locals: { products: @products }
        )
      }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/checkouts/show.html.erb
<%= turbo_stream_from current_cart %>
<div class="py-16 px-6 px-md-14 bg-white">
  <div class="d-flex mb-12 align-items-center">
    <h3 class="mb-2 mt-3">Order summary</h3>
    <span class="flex-shrink-0 d-inline-flex mt-3 ms-4 align-items-center justify-content-center rounded-circle bg-primary text-white" style="width: 32px; height: 32px;">
      <%= render "cart/item_count", count: current_cart.quantity %>
    </span>
  </div>
  <div class="mb-12 pb-16 border-bottom">
    <% current_cart.cart_items.each do |cart_item| %>
      <%= render "cart/item_line", cart_item: cart_item %>
    <% end %>
  </div>
  <div class="mb-12">
    <div class="mb-10">
      <div class="py-3 px-10 rounded-pill">
        <div class="d-flex justify-content-between">
          <span class="lead fw-bold" data-config-id="row4">Total</span>
            <%= render "cart/total_price" %>
        </div>
      </div>
    </div>
  </div>
  <%= button_to "Check out", checkout_path, data: { turbo: false }, class: "btn btn-primary w-100 text-uppercase" %>
</div>

app/views/products/_filtering.html.erb
  <div class="col-12 col-lg-3">
    <%= turbo_frame_tag "filtering" do %>
      <div class="h3">Filtering</div>
      <%= form_for :search, url: search_path do |f| %>
        <div class="input-group mb-3">
        <%= f.text_field :query, class: "form-control" %>
        <%= f.submit "Search", class: "btn btn-outline-secondary" %>
        </div>

        <%= f.select :sort, [
          ["Price Low to High", :price_lth],
          ["Price High to Low", :price_htl]
          ], { include_blank: true}, 
          class: "form-select mb-3" %>

          <div class="h4">Price</div>
          <ul class="list-group mb-3">

            <li class="list-group-item">
              <div class="form-check">
                <%= f.check_box :price, { multiple: true, class: "form-check-input" }, "lt100", nil %>
                <%= f.label :price, "< £100", class: "form-check-label" %>
              </div>
            </li>

            <li class="list-group-item">
              <div class="form-check">
                <%= f.check_box :price, { multiple: true, class: "form-check-input" }, "between100and250", nil %>
                <%= f.label :price, "£100 - £250", class: "form-check-label" %>
              </div>
            </li>

            <li class="list-group-item">
              <div class="form-check">
                <%= f.check_box :price, { multiple: true, class: "form-check-input" }, "gt250", nil %>
                <%= f.label :price, "> £250", class: "form-check-label" %>
              </div>
            </li>

          </ul>
      <% end %>
    <% end %>
  </div>

app/views/products/_show.html.erb
  <div class="row">
    <% @products.each_slice(3) do |product_group|%>
      <% product_group.each do |product| %>
        <div class="col-12 col-md-6 col-lg-4">
          <div class="card mb-5 shadow-sm" style="height: 94%;">
              <% if product.image.present? %>
                <%= image_tag product.image, class: "card-img-top" %>
              <% else %>
                <%= image_tag 'default_image.png', class: "card-img-top" %>
              <% end %>
            <div class="card-body d-flex flex-column">
              <h5 class="card-title">
                <%= product.name %><br>
              </h5>
              <p class="card-text flex-grow-1">
                <%= product.description %>
              </p>
              <%= number_to_currency(product.price) %><br>
              <%= button_to "Add to Cart", carts_add_path, params: { product: product }, class: "btn btn-primary" %>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

app/views/products/index.html.erb
<div class="row mt-4">
  <%= render "products/filtering" %>
  <div class="col-12 col-lg-9">
    <%= turbo_frame_tag "products_display" do %>
      <% render "products/show", products: @products %>
    <% end %>
    <%= paginate @products %>
  </div>
</div>