config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users

  resources :products, only: [:index, :show]

  post :search, to: "searches#show"
  get :search, to: "searches#show"

  namespace :stripe_event do
    post "/stripe/webhook", to: "webhook#event"
  end

  resource :checkout, only: [:show, :create] do
    resource :payment, only: :show
  end

  namespace :carts do
    resource :add, only: :create
    resource :reduce, only: :create
    resource :remove, only: :destroy
  end

  get 'contact_us/index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user, optional: true
  has_many :cart_items, dependent: :destroy

  enum status: {
    checkout_pending: 0,
    payment_pending: 1,
    payment_complete: 2,
    fullfilled: 3,
    cancelled: 4
  }

  def quantity
    cart_items.sum(&:quantity)
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  include ActionView::RecordIdentifier

  belongs_to :cart
  belongs_to :product

  after_create_commit do
    update_item_count
    update_total_price
  end

  after_update_commit do
    update_item_count
    update_total_price
    broadcast_replace_to cart,
                         target: dom_id(self, "quantity"),
                         partial: "cart/item_quantity",
                         locals: { cart_item: self }
  end

  after_destroy_commit do
    broadcast_remove_to cart
    update_item_count
    update_total_price
  end

  def total_price
    quantity.to_i * product.price.to_f
  end

  private

  def update_total_price
    broadcast_replace_to cart,
                         target: "total_price",
                         partial: "cart/total_price",
                         locals: { current_cart: cart }
  end

  def update_item_count
    broadcast_replace_to cart,
                         target: "cart_count",
                         partial: "cart/item_count",
                         locals: { count: cart.quantity }
  end
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/product_search.rb
class ProductSearch
  def self.call(params)
    new(params).call
  end

  def initialize(params)
    @params = params
  end

  def call
    products
      .where(search_condition)
      .where(price_condition)
      .order(sort_condition)
  end

  private

  def products
    @products ||= Product.all
  end

  def search_condition
    return unless @params.dig(:search, :query)

    ["name LIKE ?", "%#{@params.dig(:search, :query)}%"]
  end

  def price_condition
    return unless @params.dig(:search, :price)
    conditions = [].tap do |array|
      array << (..100) if @params.dig(:search, :price).include?("lt100")
      array << (100..250) if @params.dig(:search, :price).include?("bewteen100and250")
      array << (250..) if @params.dig(:search, :price).include?("gt250")
    end
    { price: conditions }
  end

  def sort_condition
    return unless @params.dig(:search, :sort)

    case @params.dig(:search, :sort)
    when "price_lth"
      { price: :asc }
    when "price_htl"
      { price: :desc }
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :cart
end

app/models/webhooks/checkout.rb
module Webhooks
  class Checkout
    def initialize(event)
      @event = event
    end

    def call
      cart = Cart.find_by!(stripe_session_id: object.id)
      cart.payment_complete!
      
    end

    private

    def object
      @event.data.object
    end

  end
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_cart
    if user_signed_in?
      cart = Cart.find_or_create_by(user: current_user)
    else
      token = cookies[:cart_token] || SecureRandom.alphanumeric(10)
      cookies[:cart_token] ||= token
      cart = Cart.find_or_create_by(token: token)
    end
    transfer_items_from_temp_cart(cart)
    cart
  end
  
  helper_method :current_cart

  def after_sign_out_path_for(resource)
    root_path
  end

  private

  def transfer_items_from_temp_cart(user_cart)
    if cookies[:cart_token].present?
      temp_cart = Cart.find_by(token: cookies[:cart_token])
      if temp_cart.present? && temp_cart != user_cart
        temp_cart.cart_items.update_all(cart_id: user_cart.id)
        temp_cart.destroy
        cookies.delete(:cart_token)
      end
    end
  end
end

app/controllers/checkouts_controller.rb
class CheckoutsController < ApplicationController
  before_action :authenticate_user!, except: :show

  def show
  end

  def create
    if user_signed_in?
      session = Stripe::Checkout::Session.create(
        billing_address_collection: :auto,
        mode: :payment,
        payment_method_types: ['card'],
        line_items: cart_items,
        success_url: checkout_payment_url,
        cancel_url: root_url
      )

      current_cart.update!(stripe_session_id: session.id)
      redirect_to session.url, allow_other_host: true
    else
      session[:redirect_to_checkout] = true
      redirect_to new_user_session_path
    end
  end

  private

  def cart_items
    current_cart.cart_items.map do |cart_item|
      {
        price_data: {
          currency: "gbp",
          product_data: {
            name: cart_item.product.name
          },
          unit_amount: cart_item.product.price.to_i * 100
        },
        quantity: cart_item.quantity
      }
    end 
  end
end

app/controllers/contact_us_controller.rb
class ContactUsController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def show
    current_cart&.payment_pending!
    current_user.cart.cart_items.destroy_all if current_user&.cart
    cookies.delete(:cart_token)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.page(params[:page]).per(12)
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def show
    @products = ProductSearch.call(params)
    respond_to do |format|
      format.turbo_stream {
        render turbo_stream: turbo_stream.replace(
          "products_display",
          partial: "products/show",
          locals: { products: @products }
        )
      }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkouts_helper.rb
module CheckoutsHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-body-tertiary sticky-top" style="padding: 0;">
  <div class="container">
    <!-- Toggle button -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <a class="navbar-brand mx-auto d-block d-sm-none">E-commerce Shop</a>

    <!-- Collapsible content -->
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: 'nav-link', style: 'line-height: 50px;' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Products', products_path, class: 'nav-link', style: 'line-height: 50px;' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Contact Us', contact_us_index_path, class: 'nav-link', style: 'line-height: 50px;' %>
        </li>
      </ul>

      <a class="navbar-brand mx-auto d-none d-lg-block">E-commerce Shop</a>

      <ul class="navbar-nav flex-row">
        <%= render 'cart/cart' %>
      </ul>
      <ul class="navbar-nav flex-row">
        <li class="nav-item dropdown me-3 me-lg-1">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-person-fill"></i>
          </a>
          <ul class="dropdown-menu dropdown-menu-lg-end">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to "Sign Out", destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: 'Are you sure you want to sign out?' }, class: "nav-link active" %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "Log In", new_user_session_path, class: "nav-link active" %>
              </li>
              <li class="nav-item">
                <%= link_to "Sign Up", new_user_registration_path, class: "nav-link active" %>
              </li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ECommerceShop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body class='bg-light'>
    <%= render 'layouts/navigation' %>
    <div class="container bg-white border pb-3">
      <%= yield %>
    </div>
  </body>
</html>